group:
  notification_view:
    name: Notifications
    view: yes
    icon: mdi:speaker
    entities:
      - group.notifications
      - group.notification_settings

  notifications:
    name: Notifications
    entities:
      - automation.notification_new_device_connected
      - automation.notification_update_available
      - automation.notification_start_up
      - automation.notification_shut_down
      - automation.notification_battery_alert
      - automation.notification_left_something_open
      - automation.notification_last_message


  notification_settings:
    name: Settings
    entities:
      - input_boolean.speech_notifications
      - input_boolean.text_notifications
      - input_select.notification_media_player_google
      - input_number.notification_google_volume
      - input_select.notification_media_player_alexa
      - input_number.notification_alexa_volume
      - input_boolean.guest_mode
      - input_boolean.notification_alert_mode


input_boolean:

  notification_alert_mode:
    name: Alert Mode
    icon: mdi:bell

  speech_notifications:
    name: Speech Notifications
    icon: mdi:bell-outline

  text_notifications:
    name: Text Notifications
    icon: mdi:message-text-outline

input_number:
  notification_google_volume:
    name: Google Volume
    icon: mdi:volume-high
    min: 0.0
    max: 1.0
    step: 0.01
  notification_alexa_volume:
    name: Alexa Volume
    icon: mdi:volume-high
    min: 0.0
    max: 1.0
    step: 0.01

input_select:
  notification_media_player_google:
    name: Source Google
    icon: mdi:speaker
    options:
###### Change these to match the FRIENDLY NAME of Google MEDIA PLAYERS #####
      - None
      - All Cast
      - Living Room Speaker
      - Living Room Cast
      - Master Bedroom Cast
      - Surround Sound Cast

  notification_media_player_alexa:
    name: Source Alexa
    icon: mdi:speaker
    options:
###### Change these to match the FRIENDLY NAME of Alexa MEDIA PLAYERS #####
      - None
      - Whole House
      - Attic Dot
      - Livingroom Dot
      - Hallway Dot
      - Bathroom Dot
      - Kitchen Dot
      - Back Porch Dot
      - Master Bedroom Dot
      - Chris and Bens Dot
      - Michaels Dot
