input_select:
  notification_media_player_google:
    name: Source Google
    icon: mdi:speaker
    options:
###### Change these to match the FRIENDLY NAME of Google MEDIA PLAYERS #####
      - All Cast
      - Living Room Speaker
      - Living Room Cast
      - Master Bedroom Cast
      - Surround Sound Cast

  notification_media_player_alexa:
    name: Source Alexa
    icon: mdi:speaker
    options:
###### Change these to match the FRIENDLY NAME of Alexa MEDIA PLAYERS #####
      - Whole House
      - Attic Dot
      - Livingroom Dot
      - Hallway Dot
      - Bathroom Dot
      - Kitchen Dot
      - Back Porch Dot
      - Master Bedroom Dot
      - Chris and Bens Dot
      - Michaels Dot
