input_select:
  notification_media_player_google:
    name: Source Google
    icon: mdi:speaker
###### Change these to match the FRIENDLY NAME of Google MEDIA PLAYERS #####
    options:
      - All Cast
      - Living Room Speaker
      - Living Room Cast
      - Master Bedroom Cast
      - Surround Sound Cast

  notification_media_player_alexa:
    name: Source Alexa
    icon: mdi:speaker
###### Change these to match the FRIENDLY NAME of Alexa MEDIA PLAYERS #####
    options:
      - Whole House
      - Attic Dot
      - Livingroom Dot
      - Hallway Dot
      - Bathroom Dot
      - Kitchen Dot
      - Back Porch Dot
      - Master Bedroom Dot
      - Chris and Bens Dot
      - Michaels Dot

sensor:
  - platform: template
    sensors:
      low_battery:
        friendly_name: 'Low Battery'
###### Change these to match the ENTITY ID of the devices whos battery levels you want to track ######
        entity_id:
          - device_tracker.joes_iphone
          - device_tracker.savannahs_iphone
        value_template: >
          {%- set threshold = 25 -%}
          {%- set domains = ['light', 'switch', 'sensor', 'lock', 'binary_sensor'] -%}
          {%- for domain in domains -%}
            {%- for item in states[domain] if ((item.attributes.battery_level is defined and item.attributes['battery_level'] | int < threshold) or ("battery" in item.name | lower and ((item.state | int < threshold and item.state|int != 0) or item.state | lower == "low"))) -%}
              {{ item.attributes.friendly_name }} (
              {%- if item.attributes.battery_level is defined -%}
                {{ item.attributes.battery_level}}
              {%- else -%}
                {{item.state}}
              {%- endif -%}%)
              {%- if not loop.last -%}
                {{', '}}
              {%- endif -%}
            {%- endfor -%}
          {%- endfor -%}
